service: nodejs

plugins:
  - serverless-plugin-lambda-insights

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  region: eu-central-1
  endpointType: REGIONAL

functions:
  nodejs:
    handler: main.main
    lambdaInsights: true
    events:
      - httpApi:
          method: 'GET'
          path: '/node'